apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: us.gcr.io/teskerti-dev/expiration
          env:
            - name: NATS_URI
              value: 'http://nats-clusterip-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'teskerti-dev'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: expiration-redis-clusterip-srv
